# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: gophersearch

builds:
- 
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  hooks:
    post: make build_linux 

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
