development:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gophersearch?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/app_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/app_production?sslmode=disable"}}
